header-from: ./.config/header.md

version: ""

formatter: markdown table

name: terraform-aws-config-recorder

content: |-
 {{ .Header }}

  # terraform-aws-config-recorder

  GitHub: [StratusGrid/terraform-aws-config-recorder](https://github.com/StratusGrid/terraform-aws-config-recorder)

  This module configures config recorder for an AWS account.

  ## Examples

  example 1
  ```hcl
  {{ include "examples/Basic/example1.tfnot" }}
  ```
  ---
  example 2
  ```hcl
  {{ include "examples/Basic/example2.tfnot" }}
  ```  
  ---
  example 3
  ```hcl
  {{ include "examples/Basic/example3.tfnot" }}
  ```  

  ---
  example 4
  ```hcl
  {{ include "examples/Multi-Region/example1.tfnot" }}
  ```
  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml`

sections:
  show:
    - header
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace